on:
  push:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test action step
        uses: ./ # Uses an action in the root directory
        with:
          url: ${{ secrets.URL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
            
          
